<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Hardware\FlexibleNullableIntConverter.cs" />
	  <Compile Remove="SystemState\AmbientDisplaySnapshot.cs" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Models\FlexibleNullableIntConverter.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Win32.SystemEvents" Version="8.0.0" />
		<PackageReference Include="Vortice.Direct3D11" Version="*" />
		<PackageReference Include="Vortice.DXGI" Version="*" />
	</ItemGroup>

</Project>