<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<LangVersion>13.0</LangVersion>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>AmbilightEngine</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<WinUISDKReferences>false</WinUISDKReferences>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Pages\SettingsGeneralPage.xaml" />
	  <None Remove="Pages\SettingsImagePage.xaml" />
	  <None Remove="Pages\SettingsMqttPage.xaml" />
	  <None Remove="Pages\SettingsStartupPage.xaml" />
	  <None Remove="Pages\SettingsWledPage.xaml" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\SplashScreen.scale-200.png" />
		<Content Include="Assets\LockScreenLogo.scale-200.png" />
		<Content Include="Assets\Square150x150Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
		<Content Include="Assets\StoreLogo.png" />
		<Content Include="Assets\Wide310x150Logo.scale-200.png" />
	</ItemGroup>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="H.NotifyIcon.WinUI" Version="2.0.115" />
		<PackageReference Include="MaterialColorUtilities" Version="0.3.0" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2270" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
		<PackageReference Include="System.Reflection.Metadata" Version="8.0.0" />
		<PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
		<PackageReference Include="MQTTnet" Version="5.0.1.1416" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AmbilightEngine.Core\AmbilightEngine.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Assets\AppIcon.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="LedStripPreviewControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Pages\SettingsGeneralPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Pages\SettingsMqttPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Pages\SettingsStartupPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Pages\SettingsImagePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Pages\SettingsWledPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Resources\ThemeResources.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Controls\" />
	</ItemGroup>

	<PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	</PropertyGroup>

	<PropertyGroup>
		<PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
		<PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
		<PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
		<PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
	</PropertyGroup>
</Project>